/**
 * generated by Xtext 2.32.0
 */
package persons.tasks.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(TaskDSLInjectorProvider.class)
@SuppressWarnings("all")
public class TaskDSLParsingTest {
}
